[colors]
ansi = [
  "#313449",
  "#C34864",
  "#7D9685",
  "#DE956F",
  "#6A8CBC",
  "#8787BF",
  "#829FB0",
  "#D5D4E0",
]
background = "#E6E6F1"
brights = [
  "#414560",
  "#B7435E",
  "#7e8f80",
  "#D88B72",
  "#6E7EBF",
  "#7170C2",
  "#728A9A",
  "#CCCBD9",
]
cursor_bg = "#829FB0"
cursor_border = "#829FB0"
cursor_fg = "#708190"
selection_bg = "#6A8CBC"
selection_fg = "#708190"
foreground = "#708190"

[metadata]
author = "FrenzyExists"
name = "Aquarium Dark"